# Generated by Django 4.1.7 on 2023-03-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_digital_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='custumer',
            new_name='customer',
        ),
    ]
