# Generated by Django 4.1.7 on 2023-03-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_custumer_shippingaddress_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipCode',
            new_name='zipcode',
        ),
    ]
